
# this voxceleb1 is doing speaker classification task!
runner:
  total_steps: 200000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 1000
  eval_step: 5000
  save_step: 2000
  max_keep: 1000
  eval_dataloaders: 
    - valid
  
optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 5000

downstream_expert: 
  datarc:
    file_path: None 
    # meta_data: None #stores the mapping label2class
    num_workers: 12
    train_batch_size: 64
    eval_batch_size: 1
    max_timestep: 128000

  modelrc:
    projector_dim: 8
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
